name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: build & test
        run: ./gradlew assemble test
      - name: archive test results
        if: failure()
        run: (cd android-material-icons/build/reports/tests; zip -r -X ../../../../test-result.zip .)
      - name: Save test output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: test-result
          path: test-result.zip
